definitions:
  datasets:
    d:
      format: AIRR
      params:
        path: C:/path/to/private-immuneml-workspace/chain_tcr_immuneml/airr_input/tcr_gamma_delta/repertoires
        metadata_file: C:/path/to/private-immuneml-workspace/chain_tcr_immuneml/airr_input/tcr_gamma_delta/metadata_cd_inflamed_vs_noninflamed.csv
        is_repertoire: true
        paired: false
        separator: "\t"
        region_type: IMGT_CDR3
        label_columns: null
        import_productive: true
        import_with_stop_codon: false
        import_out_of_frame: false
        import_illegal_characters: false
        import_empty_aa_sequences: false
        import_empty_nt_sequences: true
        import_unknown_productivity: true
  encodings:
    e:
      DeepRC: {}
  ml_methods:
    m:
      DeepRC:
        validation_part: 0.2
        add_positional_information: true
        kernel_size: 9
        n_kernels: 8
        n_additional_convs: 0
        n_attention_network_layers: 1
        n_attention_network_units: 8
        n_output_network_units: 8
        consider_seq_counts: false
        sequence_reduction_fraction: 0.1
        reduction_mb_size: 1000
        n_updates: 1
        n_torch_threads: 1
        learning_rate: 0.0001
        l1_weight_decay: 0
        l2_weight_decay: 0
        evaluate_at: 1
        sample_n_sequences: 50
        training_batch_size: 2
        n_workers: 1
        sequence_counts_scaling_fn: log
        keep_dataset_in_ram: false
        pytorch_device_name: cpu
instructions:
  i:
    type: TrainMLModel
    dataset: d
    settings:
    - encoding: e
      ml_method: m
      preprocessing: null
    assessment:
      split_strategy: random
      split_count: 1
      training_percentage: 0.7
    selection:
      split_strategy: random
      split_count: 1
      training_percentage: 0.7
    labels:
    - Inflammation1
    strategy: GridSearch
    metrics:
    - accuracy
    - balanced_accuracy
    - auc
    optimization_metric: balanced_accuracy
    number_of_processes: 1
    reports: []
    refit_optimal_model: false
    export_all_ml_settings: false
    sequence_type: AMINO_ACID
    region_type: IMGT_CDR3
